title: dirx.dev
author:
  name: Dirk Adler
description: >
  Hi, my name is Dirk Adler. Take a look at what I do, my artworks & open source projects.

permalink: pretty
exclude: [ "Gemfile", "Gemfile.lock" ]
heading_anchors: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/dirk-adler-3b484091/" }
    - { platform: xing,     user_url: "https://www.xing.com/profile/DirkAlban_Adler" }
    - { platform: mastadon, user_url: "https://genart.social/@dirx" }
    - { platform: twitter,  user_url: "https://twitter.com/d_rx" }
    - { platform: devto,    user_url: "https://dev.to/dirx" }
    - { platform: github,   user_url: "https://github.com/dirx" }

header_pages:
 - artworks-and-projects.md
 - open-source-projects.md

# Build settings
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false